---
- name: Push Docker image to ECR
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Clone Git repository
      git:
        repo: https://github.com/mreddykalyan/java_code.git
        dest: java_code

    - name: Build Docker image
      docker_image:
        path: java_code
        name: applicationdockerrepo
        tag: latest
        force_tag: yes
      environment:
        AWS_DEFAULT_REGION: "ap-southeast-2"

    - name: ECR Login
      community.general.ecr_login:
        region: "ap-southeast-2"

    - name: Tag Docker image
      docker_image:
        name: applicationdockerrepo:latest
        repository: "807993086586.dkr.ecr.ap-southeast-2.amazonaws.com/applicationdockerrepo"
        tag: latest
      environment:
        AWS_DEFAULT_REGION: "ap-southeast-2"

    - name: Push Docker image to ECR
      docker_image_push:
        name: "807993086586.dkr.ecr.ap-southeast-2.amazonaws.com/applicationdockerrepo:latest"
      environment:
        AWS_DEFAULT_REGION: "ap-southeast-2"
