---
- name: Push Docker image to ECR
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build Docker image
      docker_image:
        name:  applicationdockerrepo
        tag:  latest
        path: https://github.com/mreddykalyan/java_code.git/Dockerfile

 
   
    - name: Build Docker image           
      shell: docker build -t applicationdockerrepo:latest 
      environment:
        AWS_DEFAULT_REGION: "ap-southeast-2"
      ignore_errors: yes
      become: no
    
      
    - name: Get ECR Authentication Token
      shell: "aws ecr get-login-password --region ap-southeast-2"
      register: ecr_auth_response
      changed_when: false
      ignore_errors: true
      become: no
   

    -
    - name: Log in to ECR
      shell: "aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 807993086586.dkr.ecr.ap-southeast-2.amazonaws.com"
      register: docker_login_result
      ignore_errors: true
      when: ecr_auth_response.rc == 0
      become: no

    
    - name: Tag Docker image
      shell: docker tag applicationdockerrepo:latest 807993086586.dkr.ecr.ap-southeast-2.amazonaws.com/applicationdockerrepo:latest
      environment:
        AWS_DEFAULT_REGION: "ap-southeast-2"
      ignore_errors: yes
      become: no     
     
    - name: Push Docker image to ECR
      shell: docker push 807993086586.dkr.ecr.ap-southeast-2.amazonaws.com/applicationdockerrepo:latest
      environment:
       AWS_DEFAULT_REGION: "ap-southeast-2"
      register: push_result
      ignore_errors: yes
      become: no   
